config/routes.rb
Rails.application.routes.draw do
  resources :flights
  resources :bookings
  root 'flights#index'

end

app/models/airport.rb
class Airport < ActiveRecord::Base
  has_many :arriving_flights,  class_name: "Flight", foreign_key: "arriving_airport_id"
  has_many :departing_flights, class_name: "Flight", foreign_key: "departing_airport_id"
end

app/models/booking.rb
class Booking < ActiveRecord::Base
	belongs_to   :flight
	has_many     :passengers
	accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :arriving_airport,   class_name: "Airport"
  belongs_to :departing_airport,  class_name: "Airport"
  has_many   :bookings

  def self.list_dates
  	sorted = Flight.all.order(:departure)
    sorted.collect{ |f| f.departure.strftime('%B %d, %Y') }.uniq
  end

  def self.valid_airports
  	Airport.all.collect{ |a| [ a.code, a.id ] }
  end

  def self.search(params)
    Flight.where(arriving_airport_id:  params[:arriving_airport],
                 departing_airport_id: params[:departing_airport],
                 departure:            Flight.range(params[:departure_date]) )                            
  end

  def self.range(date)
  	unless  date.nil? || date.empty?
  		DateTime.strptime(date, '%B %d, %Y').beginning_of_day..DateTime.strptime(date, '%B %d, %Y').end_of_day
  	end
  end
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
	belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

	def new
		@flight        = Flight.find(params[:flight_id])
		@booking       = @flight.bookings.build
		build_passengers(params[:passengers], @booking)
	end

	def create
		@booking = Booking.new(booking_params)
		if @booking.save
			@booking.passengers.each { |passenger| PassengerMailer.booking_confirmation(passenger).deliver }
			redirect_to @booking
		else
			render 'new'
		end
	end

	def show
		@booking = Booking.find(params[:id])

	end


  private

  def build_passengers(passengers, booking)
  	if passengers.blank?
  		booking.passengers.build
  	else
  		passengers.to_i.times { @booking.passengers.build }
  	end
  end


  def booking_params
  	params.require(:booking).permit(:flight_id, 
  		                              :passengers_attributes => [:name, :email])
  end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
    @airport_options   = Flight.valid_airports
    @departure_options = Flight.list_dates
    @passenger_options = [1, 2, 3, 4]
    @flights           = Flight.search(params)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>Flight #<%= @flight.id %> (<%= @flight.departing_airport.code %>-<%= @flight.arriving_airport.code %>) departing <%=@flight.departure.strftime('%B, %d, %Y at %H:%M') %>
</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
<%= form_for @booking do |f| %>
  <%= f.hidden_field :flight_id, :value => @flight.id %>
	

  <%= f.fields_for :passengers do |p| %>
    <p><%= p.label :name, "Passenger Name" %>
    	<%= p.text_field :name  %>
    	<%= p.label :email, "Contact Email" %>
    <%= p.text_field :email %></p>
  <% end %>

  <%= f.submit "Confirm Details", class: "btn btn-danger" %>

<% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<h1> Booking Confirmed! </h1>

<h2>The following passengers have reserved seats on Flight #<%=@booking.flight.id%> departing from <%=@booking.flight.departing_airport.code%> to <%=@booking.flight.arriving_airport.code%> on <%=@booking.flight.departure.strftime('%B, %d, %Y at %H:%M')%></h2>

<% @booking.passengers.each do |passenger| %>

  <h2><%= passenger.name %></h2>

<% end %>

app/views/flights/index.html.erb
<%= form_tag flights_path, :method => 'get' do %>


		<h1> Flight Booking </h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">

    
  <%= select_tag(:departing_airport,      options_for_select(@airport_options),   prompt: "Departing Airport" )  %>
  <%= select_tag(:arriving_airport,       options_for_select(@airport_options),   prompt: "Arriving Airport"  )  %>
  <%= select_tag(:departure_date,         options_for_select(@departure_options), prompt: "Departure Date"    )  %>
  <%= select_tag(:passengers,             options_for_select(@passenger_options), prompt: "Passengers"        )  %> 


<%= submit_tag("Search Flights", class: "btn btn-info") %>

<% end %>

<% unless @flights.empty? %>
  <table class="table table-striped">
	  <thead>
		  <tr>
		  	<th>Select</th>
		  	<th>Flight #</th>
		  	<th>Origin</th>
		  	<th>Destination</th>
		  	<th>Departure</th>
		  	<th>Duration</th>
		  </tr>
		</thead>
	<%= form_tag new_booking_path, :method => 'get' do %>
	  <tbody>
		<% @flights.each do |flight| %>
		
			<tr>
		    <td><%= radio_button_tag(:flight_id, flight.id) %></td>
		  	<td><%= flight.id %></td>
		  	<td><%= Airport.find(flight.departing_airport_id).code   %></td>   
		    <td><%= Airport.find(flight.arriving_airport_id).code    %></td>   
		    <td><%= flight.departure.strftime('%B %d, %Y at %H:%M') %></td>
		    <td><%= flight.duration %> hours</td>
		  </tr>
		  
		<% end %>
    </tbody> 
	</table>
		<%= hidden_field_tag :passengers, params[:passengers] %>
		<%= submit_tag "Select Flight", class: "btn btn-success" %>
	<% end %>

<% end %>
  </div>
</div>



  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinFlightBooker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>